name: NoConsoleSpam Build and Release

on:
  push:
    branches: [ main ]
    tags:
      - 'v*'
  pull_request:
    branches: [ main ]

jobs:
  setup:
    name: Repository Setup
    runs-on: ubuntu-latest
    steps:
      - name: Manual repository checkout
        run: |
          echo "Performing manual checkout"
          git clone https://github.com/${{ github.repository }}.git .
          
          if [[ "${{ github.ref }}" == refs/pull/* ]]; then
            # For pull requests
            git fetch origin ${{ github.ref }} --depth=1
            git checkout FETCH_HEAD
          elif [[ "${{ github.ref }}" == refs/tags/* ]]; then
            # For tags
            git fetch --depth=1 origin +${{ github.ref }}:${{ github.ref }}
            git checkout ${{ github.ref }}
          else
            # For branches
            git checkout ${{ github.ref_name }}
          fi
          
          echo "Repository checkout complete"
          ls -la
      
      - name: Setup JDK 17
        run: |
          echo "Setting up JDK 17"
          java -version || {
            echo "Java not found, installing OpenJDK 17"
            sudo apt-get update
            sudo apt-get install -y openjdk-17-jdk
          }
          
          export JAVA_HOME=$(dirname $(dirname $(readlink -f $(which javac))))
          echo "JAVA_HOME=$JAVA_HOME"
          echo "PATH=$PATH:$JAVA_HOME/bin" >> $GITHUB_ENV
          echo "JAVA_HOME=$JAVA_HOME" >> $GITHUB_ENV
          
          # Verify installation
          java -version
          javac -version
      
      - name: Extract version from pom.xml
        id: version
        run: |
          VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
          echo "version=$VERSION" >> $GITHUB_OUTPUT
          echo "Extracted version: $VERSION"
      
      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

  build:
    name: Build Project
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - name: Repository checkout
        uses: actions/checkout@v3
      
      - name: Setup JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      
      - name: Build with Maven
        run: |
          echo "Building project with Maven"
          mvn -B clean package
          
          # Verify build success
          if [ ! -d "target" ]; then
            echo "Error: Build failed - target directory not found"
            exit 1
          fi
          
          echo "Build directory contents:"
          ls -la target/
      
      - name: Extract version from pom.xml
        id: version
        run: |
          VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
          echo "version=$VERSION" >> $GITHUB_OUTPUT
          echo "Extracted version: $VERSION"
      
      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: build-artifacts
          path: target/
          retention-days: 1

  test:
    name: Run Tests
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Repository checkout
        uses: actions/checkout@v3
      
      - name: Setup JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      
      - name: Run tests
        run: |
          echo "Running tests"
          mvn -B test

  prepare-artifacts:
    name: Prepare Release Artifacts
    needs: [build, test]
    runs-on: ubuntu-latest
    steps:
      - name: Repository checkout
        uses: actions/checkout@v3
      
      - name: Setup JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      
      - name: Download build artifacts
        uses: actions/download-artifact@v3
        with:
          name: build-artifacts
          path: target/
      
      - name: Extract version from pom.xml
        id: version
        run: |
          VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
          echo "version=$VERSION" >> $GITHUB_OUTPUT
          echo "Extracted version: $VERSION"
      
      - name: Prepare release artifacts
        run: |
          echo "Preparing release artifacts"
          # Create artifacts directory
          mkdir -p artifacts
          
          # Find exact JAR file
          ARTIFACT_NAME="noconsolespam-${{ steps.version.outputs.version }}.jar"
          ARTIFACT_PATH="target/$ARTIFACT_NAME"
          
          if [ ! -f "$ARTIFACT_PATH" ]; then
            echo "ERROR: JAR file not found at expected path: $ARTIFACT_PATH"
            echo "Contents of target directory:"
            ls -la target/
            exit 1
          fi
          
          # Copy JAR to artifacts directory with verbose output
          echo "Copying $ARTIFACT_PATH to artifacts/$ARTIFACT_NAME"
          cp -v "$ARTIFACT_PATH" "artifacts/$ARTIFACT_NAME"
          
          echo "Artifacts directory contents:"
          ls -la artifacts/
          
          # Create artifact archive
          echo "Creating artifact archive"
          tar -czvf artifacts/noconsolespam-build.tar.gz artifacts/$ARTIFACT_NAME
          
          # Save artifact name for later reference
          echo "artifact_name=$ARTIFACT_NAME" >> $GITHUB_OUTPUT
      
      - name: Upload release artifacts
        uses: actions/upload-artifact@v3
        with:
          name: release-artifacts
          path: artifacts/
          retention-days: 1

  create-release:
    name: Create GitHub Release
    if: startsWith(github.ref, 'refs/tags/v')
    needs: prepare-artifacts
    runs-on: ubuntu-latest
    steps:
      - name: Repository checkout
        uses: actions/checkout@v3
      
      - name: Download release artifacts
        uses: actions/download-artifact@v3
        with:
          name: release-artifacts
          path: artifacts/
      
      - name: Extract version from pom.xml
        id: version
        run: |
          VERSION=$(echo ${{ github.ref_name }} | sed 's/^v//')
          echo "version=$VERSION" >> $GITHUB_OUTPUT
          echo "Extracted version: $VERSION"
      
      - name: Create GitHub Release
        run: |
          echo "Creating GitHub release for version ${{ steps.version.outputs.version }}"
          
          # Install GitHub CLI
          type -p curl >/dev/null || sudo apt install curl -y
          curl -fsSL https://cli.github.com/packages/githubcli-archive-keyring.gpg | sudo dd of=/usr/share/keyrings/githubcli-archive-keyring.gpg \
          && sudo chmod go+r /usr/share/keyrings/githubcli-archive-keyring.gpg \
          && echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main" | sudo tee /etc/apt/sources.list.d/github-cli.list > /dev/null \
          && sudo apt update \
          && sudo apt install gh -y
          
          # Authenticate with GitHub CLI
          echo "${{ github.token }}" | gh auth login --with-token
          
          # Find artifact
          ARTIFACT_NAME="noconsolespam-${{ steps.version.outputs.version }}.jar"
          ARTIFACT_PATH="artifacts/$ARTIFACT_NAME"
          
          # Verify artifact exists
          if [ ! -f "$ARTIFACT_PATH" ]; then
            echo "ERROR: JAR file not found at: $ARTIFACT_PATH"
            echo "Contents of artifacts directory:"
            ls -la artifacts/
            exit 1
          fi
          
          # Create release notes
          cat > release_notes.md << EOF
          ## NoConsoleSpam ${{ steps.version.outputs.version }} Release
          
          ### Installation
          1. Install [Fabric Loader](https://fabricmc.net/use/) for Minecraft 1.20.1
          2. Download the JAR file
          3. Place it in your Minecraft mods folder
          
          For more details, see the [README](https://github.com/${{ github.repository }}/blob/main/README.md)
          EOF
          
          # Create the release
          echo "Creating release with artifact: $ARTIFACT_PATH"
          gh release create "${{ github.ref_name }}" \
            --title "NoConsoleSpam ${{ steps.version.outputs.version }}" \
            --notes-file release_notes.md \
            "$ARTIFACT_PATH"

  update-docs:
    name: Update Documentation
    if: startsWith(github.ref, 'refs/tags/v')
    needs: create-release
    runs-on: ubuntu-latest
    steps:
      - name: Repository checkout
        uses: actions/checkout@v3
      
      - name: Extract version from tag
        id: version
        run: |
          VERSION=$(echo ${{ github.ref_name }} | sed 's/^v//')
          echo "version=$VERSION" >> $GITHUB_OUTPUT
          echo "Extracted version: $VERSION"
      
      - name: Update VERSIONS Documentation
        run: |
          echo "Updating VERSIONS.md for ${{ steps.version.outputs.version }}"
          
          # Get current date
          DATE=$(date +"%Y-%m-%d")
          
          # Prepare new version entry
          NEW_ENTRY="## [${{ steps.version.outputs.version }}](https://github.com/${{ github.repository }}/releases/tag/${{ github.ref_name }}) - $DATE\n\n- [Download JAR](https://github.com/${{ github.repository }}/releases/download/${{ github.ref_name }}/noconsolespam-${{ steps.version.outputs.version }}.jar)\n- [View Changes](https://github.com/${{ github.repository }}/blob/main/CHANGES.md#$(echo ${{ steps.version.outputs.version }} | sed 's/\\./-/g'))\n"
          
          # If VERSIONS.md doesn't exist, create it
          if [ ! -f VERSIONS.md ]; then
            echo "# NoConsoleSpam Versions\n\nThis document provides links to all released versions of NoConsoleSpam.\n" > VERSIONS.md
          fi
          
          # Add new entry after header
          awk -v new_entry="$NEW_ENTRY" 'NR==4{print new_entry}1' VERSIONS.md > VERSIONS.md.tmp && mv VERSIONS.md.tmp VERSIONS.md
          
          # Configure Git for commit
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          
          # Commit the changes
          git add VERSIONS.md
          git commit -m "Update VERSIONS.md for ${{ steps.version.outputs.version }}" || echo "No changes to commit"
          
          # Push using token authentication
          git remote set-url origin https://x-access-token:${{ github.token }}@github.com/${{ github.repository }}.git
          git push origin HEAD:${GITHUB_REF#refs/heads/}

  debug-info:
    name: Debug Information
    if: always()
    needs: [setup, build, test, prepare-artifacts]
    runs-on: ubuntu-latest
    steps:
      - name: Repository checkout
        uses: actions/checkout@v3
      
      - name: Download build artifacts
        uses: actions/download-artifact@v3
        with:
          name: build-artifacts
          path: target/
          
      - name: Download release artifacts
        uses: actions/download-artifact@v3
        with:
          name: release-artifacts
          path: artifacts/
          
      - name: Debug information
        run: |
          echo "=== Debug Information ==="
          echo "Current directory: $(pwd)"
          echo "Repository contents:"
          ls -la
          
          echo "Target directory contents:"
          ls -la target/ || echo "No target directory found"
          
          echo "Artifacts directory contents:"
          ls -la artifacts/ || echo "No artifacts directory found"
          
          echo "Environment variables:"
          echo "VERSION: $(mvn help:evaluate -Dexpression=project.version -q -DforceStdout || echo 'N/A')" 